server_name: "nats-main"

# Клиентский порт
port: 4222

# Порт мониторинга (ограничить через firewall)
http_port: 8222

jetstream {
  store_dir: "/data/jetstream"
  max_mem: 1Gb # Ограничения по оперативке
  max_file: 12Gb # Ограничения по диску
}

# Базовые лимиты для защиты от перегрузки:
# Максимум одновременных клиентских подключений к серверу NATS.
max_connections: 2000
# Максимальный размер одного публикуемого сообщения.
max_payload: 1MB
